# Generated by Django 5.2.6 on 2025-10-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasgoApp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
