# Generated by Django 5.2.6 on 2025-10-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasgoApp', '0003_order_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
