# Generated by Django 5.2.6 on 2025-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasgoApp', '0005_alter_order_exchange_alter_order_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('gas_size', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
