# Generated by Django 5.2.6 on 2026-01-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasgoApp', '0007_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics'),
        ),
    ]
